---
# tasks file for nginx

- name: Install Nginx
  become: yes
  ansible.builtin.package:
    name: nginx
    state: present

- name: Ensure Nginx is enabled and started
  become: yes
  ansible.builtin.service:
    name: nginx
    state: started
    # enabled: yes

- name: Get Nginx port from local Consul
  uri:
    url: "http://consul:8500/v1/kv/port-nginx?raw"
    return_content: yes
  register: nginx_port_response
  delegate_to: localhost
  become: false

- name: Set Nginx port fact
  set_fact:
    nginx_port: "{{ nginx_port_response.content }}"

- name: Show which port will be used for Nginx
  debug:
    msg: "Nginx will run on port {{ nginx_port }}"

- name: Deploy nginx.conf rendered with the selected port
  become: yes
  template:
    src: templates/index.html.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx

- name: Deploy custom HTML page
  become: yes
  template:
    src: templates/index.html.j2 
    dest: /var/www/html/index.html
  notify: Restart Nginx
