---
- name: Deploy and rolling update Nginx
  hosts: webserver
  vars:
    target_group_arn: "arn:aws:elasticloadbalancing:il-central-1:314525640319:targetgroup/tg-oleg/7760255c09ddd38b"
    aws_region: "il-central-1"
  roles:
    - role: nginx